export interface CaseStudy {
  id: string;
  client: string;
  tagline: string;
  category: string;
  summary: string[];
  stats: { value: string; label: string }[];
  services: string[];
  quote: { text: string; author: string; role: string };
}

export const caseStudies: CaseStudy[] = [
  {
    id: 'airfocus',
    client: 'airfocus',
    tagline: 'Product management, made modular',
    category: '(SaaS)',
    summary: [
      'For airfocus, we built and ran a complete PPC strategy to attract the right audience and increase conversions.',
      'We also led all SEO and content efforts, growing organic traffic to over 100K monthly visitors and turning it into the company\u2019s main source of user acquisition.',
    ],
    stats: [
      { value: '\u20AC720k', label: 'annual ad spend optimized' },
      { value: '100k+', label: 'monthly organic users from SEO' },
    ],
    services: ['Performance Marketing', 'Organic Growth', 'Content Strategy'],
    quote: {
      text: 'The Maiac team had a genuine interest in not only our product & brand but also our continued growth. Their expertise and delivery helped us greatly in reaching important milestones.',
      author: 'Valentin Firak',
      role: 'CRO at airfocus by Lucid',
    },
  },
  {
    id: 'blugento',
    client: 'Blugento',
    tagline: 'E-commerce, given a voice',
    category: '(E-commerce)',
    summary: [
      'Maiac supported Blugento from the product\u2019s early days, shaping the brand, positioning, and overall communication strategy. We worked closely with the founding team to turn a technical e-commerce platform into a clear, credible value proposition.',
      'As Blugento matured, we supported go-to-market initiatives and expansion efforts, including positioning the platform for Western European markets through a new brand line, Zento, treating marketing as a growth partner rather than a promotional layer.',
    ],
    stats: [
      { value: '400+', label: 'monthly B2B leads' },
      { value: '>90%', label: 'business generated by SEO & PPC' },
    ],
    services: ['Brand & Positioning', 'Go-to-Market', 'Communications Strategy'],
    quote: {
      text: 'I\u2019ve worked with Maiac for over a decade on various internal and external projects at Blugento. We\u2019ve built marketing and branding strategies, implemented social media campaigns, and set up ad campaigns that generated sustainable growth.',
      author: 'Vlad Stanescu',
      role: 'CEO at Blugento',
    },
  },
  {
    id: 'rebeldot',
    client: 'RebelDot',
    tagline: 'From startup to scale-up',
    category: '(Tech Services)',
    summary: [
      'We defined the brand narrative, tone of voice, and messaging pillars, then turned them into a coherent website structure and organic content system that speaks to technical founders, enterprise clients, and future talent alike.',
      'Alongside brand building, we supported RebelDot\u2019s go-to-market strategy in the Nordic countries, adapted the core narrative around engineering rigor, trust, and long-term partnerships, and later backed the repositioning toward RebelDot AI.',
    ],
    stats: [
      { value: '6+', label: 'years of partnership' },
      { value: '1', label: 'lead engine, built from zero' },
    ],
    services: ['Strategy & Consultancy', 'Sales Enablement', 'Website & Platforms', 'Organic Growth', 'Branding & PR', 'Events'],
    quote: {
      text: 'I\u2019ve worked with Andreea for over six years, starting right after RebelDot launched. Together, we built the foundation of our demand generation funnel and defined a brand voice that truly represents who we are.',
      author: 'Tudor Ciuleanu',
      role: 'CEO at RebelDot',
    },
  },
  {
    id: 'nooka-space',
    client: 'Nooka Space',
    tagline: 'A new category, made clear',
    category: '(PropTech)',
    summary: [
      'We built the brand narrative around focus, privacy, and productivity, shifting the conversation from product aesthetics to real business value. The messaging framework supports sales, partnerships, and investor conversations.',
      'Maiac also supported Nooka Space\u2019s go-to-market efforts across Western Europe with a scalable, culturally adaptable communication system, positioning the brand as a serious infrastructure solution for modern offices.',
    ],
    stats: [
      { value: '15', label: 'years of working together' },
      { value: 'WEU', label: 'go-to-market coverage' },
    ],
    services: ['Strategy & Consultancy', 'Website & Platforms', 'Organic Growth', 'Sales Enablement', 'Branding & PR', 'Events'],
    quote: {
      text: 'I\u2019ve worked with this team for the last 15 years on numerous projects. They are my go-to team for creativity and business objective driven marketing.',
      author: 'Sandu Babasan',
      role: 'CEO at Nooka Space',
    },
  },
];

export const services = [
  {
    id: 'strategy',
    name: 'Strategy',
    blurb: 'Where to play and how to win: direction before deliverables.',
    items: [
      'Brand and business positioning',
      'New markets positioning',
      'Growth strategy and performance tracking',
      'Marketing organization and team structure',
      'Strategy advisory',
    ],
  },
  {
    id: 'brand',
    name: 'Brand',
    blurb: 'A story your market can\u2019t ignore, built into a system.',
    items: [
      'Story and messaging development',
      'Visual identity and design systems',
      'Tone of voice and communication guidelines',
      'Brand architecture',
      'Narrative frameworks and content systems',
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    blurb: 'We market more, so your team can sell more.',
    items: [
      'Demand generation and lead funnels',
      'Content marketing',
      'Paid media strategy and management',
      'Website optimization and CRO',
      'Analytics, reporting, and performance dashboards',
    ],
  },
  {
    id: 'development',
    name: 'Development',
    blurb: 'Your website and product experience are part of your marketing, too.',
    items: [
      'Website and platform design & development',
      'Martech setup (tracking, CRM, automation)',
      'AI-powered campaign operations',
      'Workflow automation and data integration',
      'Conversion infrastructure',
    ],
  },
];

export const methodSteps = [
  {
    n: '01',
    title: 'We do the strategy.',
    text: 'You get direction, clarity, and a plan that tells you where to play and how to win.',
  },
  {
    n: '02',
    title: 'We build a story your market can\u2019t ignore.',
    text: 'Your customers need you to stand out, so we help you do exactly that.',
  },
  {
    n: '03',
    title: 'We market more, so your team can sell more.',
    text: 'We reach the right people and help your sales team convert faster.',
  },
  {
    n: '04',
    title: 'We use technology to compound business growth.',
    text: 'Your website and product user experience are part of your marketing, too.',
  },
];

export const philosophy = [
  {
    n: '(1)',
    text: 'Great marketing isn\u2019t about more assets. It\u2019s about sharper stories.',
  },
  {
    n: '(2)',
    text: 'AI is a force multiplier for individuals and organizations that care about the craft.',
  },
  {
    n: '(3)',
    text: 'Deliverables are easy. Value is hard. And we\u2019re here for the hard part.',
  },
];

export const testimonials = caseStudies.map((c) => ({
  ...c.quote,
  company: c.client,
}));

export const clients = ['airfocus by Lucid', 'Blugento', 'RebelDot', 'Nooka Space'];

export const articles = [
  {
    title: 'Great marketing isn’t more assets — it’s sharper stories',
    tag: 'Strategy',
  },
  {
    title: 'AI as a force multiplier for marketing teams that care about craft',
    tag: 'AI',
  },
  {
    title: 'Deliverables are easy. Value is hard.',
    tag: 'Growth',
  },
];

export const contact = {
  email: 'hello@maiac.agency',
  address: 'Mihai Eminescu 14, Cluj-Napoca',
};
